name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  GREEN: '\033[0;32m'
  NO_COLOR: '\033[0m'

jobs:
  linting:
    runs-on: ubuntu-latest
    name: Lint testing
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      id: cache
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Setup dependencies
      run: |
        pip install pre-commit==3.5.0

    - name: Linting
      run: |
        pre-commit run check-yaml --all-files --verbose
        pre-commit run check-yaml --all-files --verbose
        pre-commit run check-toml --all-files --verbose
        pre-commit run check-json --all-files --verbose
        pre-commit run check-ast --all-files --verbose
        pre-commit run requirements-txt-fixer --all-files --verbose
        pre-commit run trailing-whitespace --all-files --verbose
        pre-commit run end-of-file-fixer --all-files --verbose
        pre-commit run double-quote-string-fixer --all-files --verbose
        pre-commit run add-trailing-comma --all-files --verbose
        pre-commit run black --all-files --verbose
        pre-commit run pretty-format-yaml --all-files --verbose
        pre-commit run pycln --all-files --verbose
        pre-commit run isort --all-files --verbose
        pre-commit run ruff --all-files --verbose
        echo -e "${GREEN}Job completed successfully${NC}"
